# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude: 'src/lib/internal/.*'
      - id: check-added-large-files
      - id: fix-byte-order-marker
      - id: destroyed-symlinks
      - id: mixed-line-ending
      - id: check-case-conflict
      - id: detect-private-key
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: 'v3.0.0-alpha.0' # Use the sha / tag you want to point at
    hooks:
      - id: prettier
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: 'v8.23.1' # Use the sha / tag you want to point at
    hooks:
      - id: eslint
        files: \.[jt]sx?$ # *.js, *.jsx, *.ts and *.tsx
        types: [file]
        additional_dependencies:
          - 'eslint@8.23.1'
          - '@typescript-eslint/eslint-plugin@5.37.0'
          - '@typescript-eslint/parser@5.37.0'
          - 'eslint-config-prettier@8.5.0'
          - 'eslint-plugin-eslint-comments@3.2.0'
          - 'eslint-plugin-functional@4.3.0'
          - 'eslint-plugin-import@2.26.0'
